name: textlint
on:
  pull_request:

jobs:
  textlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: articles
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
